version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: real-estate-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: real_estate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real-estate-network

networks:
  real-estate-network:
    driver: bridge

volumes:
  postgres_data: 